version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - laravel_net

  db:
    image: mysql:8.0.31
    environment:
      MYSQL_DATABASE: base
      MYSQL_ROOT_PASSWORD: 0Paulo123#
    ports:
      - 30306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_net

networks:
  laravel_net:
    driver: bridge
